#!/bin/bash
set -e
if [ "$1" = "download" ]; then
	LATEST_VERSION=$(curl -L -s -H 'Accept: application/json' https://github.com/abextm/osrs-cache/releases/latest | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
	echo "Downloading $LATEST_VERSION"
	curl -L "https://github.com/abextm/osrs-cache/releases/download/$LATEST_VERSION/dump-$LATEST_VERSION.tar.gz" | tar xz
	exit
fi
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
NEWDIR="$DIR/scripts"
FI="$1"
if [ "$1" = "last" ]; then
	unset -v FI
	for ifi in "$NEWDIR"/*.js; do
		[[ $ifi -nt $FI ]] && FI=$ifi
	done
fi
if [ -z "$FI" ]; then
	DATE="$(date +"%m_%d_%y_%H_%M_%S")"
	FI="$NEWDIR/$DATE.js"
else	
	if [[ ${FI:0:1} != '/' ]]; then
		FI="$NEWDIR/$FI"
	fi
fi
if [ ! -f "$FI" ]; then
	touch "$FI"
	touch "$FI.out"
fi
vim -c "source $DIR/nipple.vim" -O "$FI" "$FI.out"